services:
  - type: web_service
    name: ad-verification-tool  # Replace with your desired name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    wsgi: true
