services:
  - type: web
    name: lead-verifier-backend
    env: python
    rootDir: project
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
