services:
  - type: web
    name: lead-verifier-backend
    env: python
    rootDir: project
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
